# Form implementation generated from reading ui file 'c:\Project\new_exim_device\Device_manager\frm_popup_device_manager.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_popup_device_manager(object):
    def setupUi(self, frm_popup_device_manager):
        frm_popup_device_manager.setObjectName("frm_popup_device_manager")
        frm_popup_device_manager.resize(1258, 597)
        self.gridLayout = QtWidgets.QGridLayout(frm_popup_device_manager)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=frm_popup_device_manager)
        self.frame.setStyleSheet("color: rgb(255, 213, 126);\n"
"background-color: rgb(54, 54, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 100, 211, 41))
        self.label.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 211, 41))
        self.label_2.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label_2.setObjectName("label_2")
        self.lbl_ID = QtWidgets.QLabel(parent=self.frame)
        self.lbl_ID.setGeometry(QtCore.QRect(1150, 50, 61, 31))
        self.lbl_ID.setStyleSheet("color: rgb(68, 80, 105);")
        self.lbl_ID.setText("")
        self.lbl_ID.setObjectName("lbl_ID")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(880, 10, 352, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_username = QtWidgets.QLineEdit(parent=self.widget)
        self.txt_username.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_username.setObjectName("txt_username")
        self.horizontalLayout.addWidget(self.txt_username)
        self.cmb_device_name = QtWidgets.QComboBox(parent=self.frame)
        self.cmb_device_name.setGeometry(QtCore.QRect(270, 100, 301, 41))
        self.cmb_device_name.setMouseTracking(False)
        self.cmb_device_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cmb_device_name.setEditable(True)
        self.cmb_device_name.setCurrentText("")
        self.cmb_device_name.setDuplicatesEnabled(False)
        self.cmb_device_name.setObjectName("cmb_device_name")
        self.cmb_location = QtWidgets.QComboBox(parent=self.frame)
        self.cmb_location.setGeometry(QtCore.QRect(270, 250, 331, 41))
        self.cmb_location.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cmb_location.setEditable(False)
        self.cmb_location.setObjectName("cmb_location")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(30, 250, 161, 41))
        self.label_17.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label_17.setObjectName("label_17")
        self.txt_remark = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_remark.setGeometry(QtCore.QRect(270, 350, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Phetsarath OT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.txt_remark.setFont(font)
        self.txt_remark.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.txt_remark.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Phetsarath OT\";")
        self.txt_remark.setText("")
        self.txt_remark.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.txt_remark.setDragEnabled(False)
        self.txt_remark.setPlaceholderText("")
        self.txt_remark.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.txt_remark.setObjectName("txt_remark")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 350, 161, 41))
        self.label_18.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label_18.setObjectName("label_18")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(660, 440, 541, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_insert = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_insert.setEnabled(True)
        self.btn_insert.setStyleSheet("background-color: rgb(0, 127, 108);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_insert.setIconSize(QtCore.QSize(20, 20))
        self.btn_insert.setObjectName("btn_insert")
        self.horizontalLayout_2.addWidget(self.btn_insert)
        self.btn_edit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 127);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_edit.setIconSize(QtCore.QSize(25, 25))
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_2.addWidget(self.btn_edit)
        self.btn_clear = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_clear.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_clear.setIconSize(QtCore.QSize(25, 25))
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_2.addWidget(self.btn_clear)
        self.btn_cancel = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_cancel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_cancel.setIconSize(QtCore.QSize(25, 25))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.label_19 = QtWidgets.QLabel(parent=self.frame)
        self.label_19.setGeometry(QtCore.QRect(30, 200, 161, 41))
        self.label_19.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label_19.setObjectName("label_19")
        self.cmb_used_by = QtWidgets.QComboBox(parent=self.frame)
        self.cmb_used_by.setGeometry(QtCore.QRect(270, 300, 331, 41))
        self.cmb_used_by.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cmb_used_by.setEditable(True)
        self.cmb_used_by.setObjectName("cmb_used_by")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(30, 300, 161, 41))
        self.label_21.setStyleSheet("font: 18pt \"Phetsarath OT\";\n"
"color: rgb(255, 213, 126);\n"
"")
        self.label_21.setObjectName("label_21")
        self.lbl_did_ = QtWidgets.QLabel(parent=self.frame)
        self.lbl_did_.setGeometry(QtCore.QRect(1110, 100, 81, 41))
        self.lbl_did_.setStyleSheet("color: rgb(1, 114, 127);\n"
"color: rgb(255, 0, 0);")
        self.lbl_did_.setText("")
        self.lbl_did_.setObjectName("lbl_did_")
        self.btn_search_device_name = QtWidgets.QPushButton(parent=self.frame)
        self.btn_search_device_name.setGeometry(QtCore.QRect(580, 100, 61, 41))
        self.btn_search_device_name.setStyleSheet("background-color: rgb(255, 213, 126);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_search_device_name.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Project\\new_exim_device\\Device_manager\\../../../Users/AlexP/PycharmProjects/pythonProject/PythonPOS/icon/search-alt-regular-60.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_search_device_name.setIcon(icon)
        self.btn_search_device_name.setIconSize(QtCore.QSize(40, 40))
        self.btn_search_device_name.setObjectName("btn_search_device_name")
        self.btn_search_location = QtWidgets.QPushButton(parent=self.frame)
        self.btn_search_location.setGeometry(QtCore.QRect(610, 250, 61, 41))
        self.btn_search_location.setStyleSheet("background-color: rgb(255, 213, 126);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_search_location.setText("")
        self.btn_search_location.setIcon(icon)
        self.btn_search_location.setIconSize(QtCore.QSize(40, 40))
        self.btn_search_location.setObjectName("btn_search_location")
        self.btn_search_usedby = QtWidgets.QPushButton(parent=self.frame)
        self.btn_search_usedby.setGeometry(QtCore.QRect(610, 300, 61, 41))
        self.btn_search_usedby.setStyleSheet("background-color: rgb(255, 213, 126);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Phetsarath OT\";")
        self.btn_search_usedby.setText("")
        self.btn_search_usedby.setIcon(icon)
        self.btn_search_usedby.setIconSize(QtCore.QSize(40, 40))
        self.btn_search_usedby.setObjectName("btn_search_usedby")
        self.lbl_serial_number = QtWidgets.QLabel(parent=self.frame)
        self.lbl_serial_number.setGeometry(QtCore.QRect(270, 150, 381, 41))
        self.lbl_serial_number.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Phetsarath OT\";")
        self.lbl_serial_number.setText("")
        self.lbl_serial_number.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lbl_serial_number.setObjectName("lbl_serial_number")
        self.cmb_status = QtWidgets.QComboBox(parent=self.frame)
        self.cmb_status.setGeometry(QtCore.QRect(270, 200, 331, 41))
        self.cmb_status.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cmb_status.setEditable(False)
        self.cmb_status.setObjectName("cmb_status")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(frm_popup_device_manager)
        QtCore.QMetaObject.connectSlotsByName(frm_popup_device_manager)

    def retranslateUi(self, frm_popup_device_manager):
        _translate = QtCore.QCoreApplication.translate
        frm_popup_device_manager.setWindowTitle(_translate("frm_popup_device_manager", "Form Devices Manager"))
        self.label.setText(_translate("frm_popup_device_manager", "Device Name"))
        self.label_2.setText(_translate("frm_popup_device_manager", "Serial Number"))
        self.label_17.setText(_translate("frm_popup_device_manager", "Location "))
        self.label_18.setText(_translate("frm_popup_device_manager", "Remark"))
        self.btn_insert.setText(_translate("frm_popup_device_manager", " ເພີ່ມຂໍ້ມູນ"))
        self.btn_edit.setText(_translate("frm_popup_device_manager", "ແກ້ໄຂ"))
        self.btn_clear.setText(_translate("frm_popup_device_manager", "ລ້າງ"))
        self.btn_cancel.setText(_translate("frm_popup_device_manager", "ຍົກເລີກ"))
        self.label_19.setText(_translate("frm_popup_device_manager", "Status"))
        self.label_21.setText(_translate("frm_popup_device_manager", "Used by"))
