# Form implementation generated from reading ui file 'c:\Project\new_exim_device\Register\form_register.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormRegister(object):
    def setupUi(self, FormRegister):
        FormRegister.setObjectName("FormRegister")
        FormRegister.resize(400, 260)
        self.txt_name = QtWidgets.QTextEdit(parent=FormRegister)
        self.txt_name.setGeometry(QtCore.QRect(130, 30, 161, 31))
        self.txt_name.setObjectName("txt_name")
        self.txt_password = QtWidgets.QTextEdit(parent=FormRegister)
        self.txt_password.setGeometry(QtCore.QRect(130, 110, 161, 31))
        self.txt_password.setObjectName("txt_password")
        self.btn_register = QtWidgets.QPushButton(parent=FormRegister)
        self.btn_register.setGeometry(QtCore.QRect(180, 160, 113, 32))
        self.btn_register.setObjectName("btn_register")
        self.btn_close = QtWidgets.QPushButton(parent=FormRegister)
        self.btn_close.setGeometry(QtCore.QRect(180, 190, 113, 32))
        self.btn_close.setObjectName("btn_close")
        self.txt_username = QtWidgets.QTextEdit(parent=FormRegister)
        self.txt_username.setGeometry(QtCore.QRect(130, 70, 161, 31))
        self.txt_username.setObjectName("txt_username")
        self.widget = QtWidgets.QWidget(parent=FormRegister)
        self.widget.setGeometry(QtCore.QRect(50, 30, 81, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(FormRegister)
        QtCore.QMetaObject.connectSlotsByName(FormRegister)

    def retranslateUi(self, FormRegister):
        _translate = QtCore.QCoreApplication.translate
        FormRegister.setWindowTitle(_translate("FormRegister", "Form"))
        self.btn_register.setText(_translate("FormRegister", "Register"))
        self.btn_close.setText(_translate("FormRegister", "Close"))
        self.label.setText(_translate("FormRegister", "Name"))
        self.label_3.setText(_translate("FormRegister", "Username"))
        self.label_2.setText(_translate("FormRegister", "Password"))
