# Form implementation generated from reading ui file 'c:\Project\new_exim_device\Auth\frm_login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormLogin(object):
    def setupUi(self, FormLogin):
        FormLogin.setObjectName("FormLogin")
        FormLogin.resize(400, 300)
        self.btn_login = QtWidgets.QPushButton(parent=FormLogin)
        self.btn_login.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.btn_login.setObjectName("btn_login")
        self.btn_register = QtWidgets.QPushButton(parent=FormLogin)
        self.btn_register.setGeometry(QtCore.QRect(190, 190, 113, 32))
        self.btn_register.setObjectName("btn_register")
        self.label = QtWidgets.QLabel(parent=FormLogin)
        self.label.setGeometry(QtCore.QRect(90, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=FormLogin)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 81, 16))
        self.label_2.setObjectName("label_2")
        self.txt_username = QtWidgets.QLineEdit(parent=FormLogin)
        self.txt_username.setGeometry(QtCore.QRect(90, 50, 211, 31))
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(parent=FormLogin)
        self.txt_password.setGeometry(QtCore.QRect(90, 110, 211, 31))
        self.txt_password.setObjectName("txt_password")

        self.retranslateUi(FormLogin)
        QtCore.QMetaObject.connectSlotsByName(FormLogin)

    def retranslateUi(self, FormLogin):
        _translate = QtCore.QCoreApplication.translate
        FormLogin.setWindowTitle(_translate("FormLogin", "Form"))
        self.btn_login.setText(_translate("FormLogin", "Login"))
        self.btn_register.setText(_translate("FormLogin", "Register"))
        self.label.setText(_translate("FormLogin", "Username"))
        self.label_2.setText(_translate("FormLogin", "Password"))
        

